[[libcgal_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aa358998215bff8021eeafc13c2aea704e1f94e1"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "2b30c3eeeb8d14ffd9c08c7dbdd9b465062addb9cc5a60697536b50f3149edd0"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.15.0+0/libcgal_julia.v0.15.0.aarch64-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d583ff87a873953acc2ee2bf8ed4f00e610ce21f"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "33bc381463493cc86eb53ff5f7865a2bb2624ce39fa4cd16a333bb870348e0b7"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.15.0+0/libcgal_julia.v0.15.0.i686-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a28077999779d7b3736951fe765c325edabf0f42"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "c2afe6cb9dd5aad13621fba089a5ee3b2abf8c43869e447305bdfddeb7291531"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.15.0+0/libcgal_julia.v0.15.0.i686-w64-mingw32-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8730e205da7f801b0eaeab199b65578f9367fddd"
os = "macos"

    [[libcgal_julia.download]]
    sha256 = "47e29566d244411f758b852c25bbaee2b2e1dfd9fc19e89700aecc246b613ea7"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.15.0+0/libcgal_julia.v0.15.0.x86_64-apple-darwin14-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "27a7a2de46d9e502696cc8df7da3927db1c1f4b9"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "01ff576cc64d748daf97034b2c303f8320730f6e118d27cb018a0359abb322dc"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.15.0+0/libcgal_julia.v0.15.0.x86_64-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f735025ab2b0af789a755941d46192ef4ef2a02f"
os = "freebsd"

    [[libcgal_julia.download]]
    sha256 = "87fb247e0aa5332e58a38230d726b831a6f1dae43b23ebee7626d7fa20290450"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.15.0+0/libcgal_julia.v0.15.0.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "554656cdc6a63a2f3a557d17da9e4b2c5752970a"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "b58b394a31b5b8db93d6018f32311843b3f5fd8ab9d41845c6bd6e5b786a8803"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.15.0+0/libcgal_julia.v0.15.0.x86_64-w64-mingw32-cxx11.tar.gz"
