[[libcgal_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e11cc25190d8180d05a39380cd55e0311cc3ed5a"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "c1cffb622abcc1e7b34112624525a4e2ad0e72ae03c311a799c25e36550bb197"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.5+1/libcgal_julia.v0.17.5.aarch64-linux-gnu-cxx03.tar.gz"
[[libcgal_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cb71856096c7150416443e55c1d1318ad5597141"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "9cbc005f00454df9858dff43d4752c7a55511d721e5359d7ee0d31429ee258a8"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.5+1/libcgal_julia.v0.17.5.aarch64-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f3dd8e8bc406fa7792eb55ade25a7cdd10988232"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "52470df9d056d76c9202969541565fb1a033e2bd9a21faf44a7817137e99e004"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.5+1/libcgal_julia.v0.17.5.aarch64-linux-musl-cxx03.tar.gz"
[[libcgal_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "36d7877d0ced4b499af6f94dfcd08f5d61418b2a"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "4b85fc386c8e92b03a79b37b836d96e43dd2037d2380b183c050f451185b584c"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.5+1/libcgal_julia.v0.17.5.aarch64-linux-musl-cxx11.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d6363d620cbf48ddd8e1d0a92c50841ba95ffb31"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "649e7c8a877585708aca6e470cf2f9e3d61f5bfd79ec85b09e2e803b42620250"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.5+1/libcgal_julia.v0.17.5.i686-linux-gnu-cxx03.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4dcde367f39f10335dc353f2c689535b6a07c8af"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "0aa1c7ad2e2e1aeb3c19b0c99783d11c563c6c760d2d3fddc485ebd6b823c2c8"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.5+1/libcgal_julia.v0.17.5.i686-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f95eb583554c8cafc36eb8c0fd76548e64c1aa68"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "7ed1cd1070fe33009a80c55e352c70678e36700cf665671db1c2cb551101ae78"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.5+1/libcgal_julia.v0.17.5.i686-w64-mingw32-cxx03.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d9aada869781505e3851a86d55bac2f9f365c43b"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "6d3496edbae3a8ec021683b3d5283585e7ca40a884ce41817594609552bdf51d"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.5+1/libcgal_julia.v0.17.5.i686-w64-mingw32-cxx11.tar.gz"
[[libcgal_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f9888790dba3c194d827d4407842dd38b1071c9f"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "5e918ba433c859e27b8c3bee1a63d90126424d872111d7896c1ec54070f37d8b"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.5+1/libcgal_julia.v0.17.5.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libcgal_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b2ad1ba996531a618d160758de6042128ec28cbd"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "a423e231972e191a075fc48fa7b8c90a6407b3f0895d0fa152dceb9b4129c552"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.5+1/libcgal_julia.v0.17.5.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
git-tree-sha1 = "cc8aafa9b1ffb55b887d47c1391e345154e9d41b"
os = "macos"

    [[libcgal_julia.download]]
    sha256 = "a802ee441a290b4fa24b4fe9d8ab04864a3b9e7d1d85be53f75f25102247ba5c"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.5+1/libcgal_julia.v0.17.5.x86_64-apple-darwin.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1bff38cad0ec01f9829b3addf6d3ab4b4bc03555"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "8ccd2b48d410c280c75798697b551890602adc1980be27a42c4f017a6705b83d"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.5+1/libcgal_julia.v0.17.5.x86_64-linux-gnu-cxx03.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "95ebdcbcb0a2e41de6b785eceba71f97d16d44b1"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "7fb48b8e665d846fe5654d507188a2ede21bc39ba1a47bb43893e6079db0a3ef"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.5+1/libcgal_julia.v0.17.5.x86_64-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "043e3f7d4f08eab88d0349355ae8f5e4a2ce0ffd"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "9014dc82776d04c1ac319d3af0a3c1d59ee2c57396bcf83fbb3f4700e221da7c"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.5+1/libcgal_julia.v0.17.5.x86_64-linux-musl-cxx03.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b86fe91259e5563ac3ee18f9a2843049a1c795c1"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "c3b79b190392972c5951453fd408929b522103c0e24066bdb8dd18e79c184552"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.5+1/libcgal_julia.v0.17.5.x86_64-linux-musl-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
git-tree-sha1 = "28224f5dbefe5db56c661d4e202606e9ecc22a60"
os = "freebsd"

    [[libcgal_julia.download]]
    sha256 = "675f5237d2c024a993a8d94e906d183f797b093f8e6ab80b32595be3e884449d"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.5+1/libcgal_julia.v0.17.5.x86_64-unknown-freebsd.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "897e0d91a02d1c5b7fdfa0f37b1ba0bde60f62ef"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "1e46b852dde5be7c9b11bfd0a28a6fb00fa5e69e96a3f69b2f893c7e7ae3b44a"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.5+1/libcgal_julia.v0.17.5.x86_64-w64-mingw32-cxx03.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "588e3dfd7181ca2d81d5c30ea07da2f0b70f8b0c"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "ba58817148bd7c75158579c92da072a3a1cbb9dcbda163df3a51cc98a0e269ba"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.5+1/libcgal_julia.v0.17.5.x86_64-w64-mingw32-cxx11.tar.gz"
