[[libcgal_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3f51577ddf604d68308231fa8da488546ac7f0aa"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "7ea092589fad8b8618b88bac2240c8cb50fa330b3dd8b20751401a22f8b39432"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.3+1/libcgal_julia.v0.17.3.aarch64-linux-gnu-cxx03.tar.gz"
[[libcgal_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3b49624d7a1b1ee3fcada4fc8082db74200336a3"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "148566b24af117676086c5bbb50f9ed81c9915fac4dcf98189e06645aaf903f4"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.3+1/libcgal_julia.v0.17.3.aarch64-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bd34993874c53b26fa11b94213b861d8e8c7c2d5"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "bab9961fb9b6d95dd882fafce180bdaa1040242f7f1d81eb615cba13bc00cfb2"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.3+1/libcgal_julia.v0.17.3.aarch64-linux-musl-cxx03.tar.gz"
[[libcgal_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "989dd4e8f8f492a1103b8ee093f9f9d0c00a8856"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "7e38422def370a71ac1011bc4f71d7e37b8ee06e437222d4c7bcaa462f304380"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.3+1/libcgal_julia.v0.17.3.aarch64-linux-musl-cxx11.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "33f223a44df335640926665e8ab8823cf4a3dc59"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "1c95a495f7c0d46b208ae5f55184fca6526f2f4294b9070489d953ddf3010498"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.3+1/libcgal_julia.v0.17.3.i686-linux-gnu-cxx03.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a213d9e0b85b9ff0d061983fb6070a634e5e5732"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "c6bafbe517131d09f881c94f3946900d1c5e88a7c75dbcd70e338e854e934920"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.3+1/libcgal_julia.v0.17.3.i686-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0bbf5c0ed9bf4133e014c524006e03ec2900b283"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "925f4b7404c13ccf073a7d5ad162ed67c5adbfed6825a47d3807c9cb431b0f9e"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.3+1/libcgal_julia.v0.17.3.i686-w64-mingw32-cxx03.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "487e13f6f91fe42eee39a2d5aff847ef9f0fe368"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "9d8e467e25e91312518d180a4afe3a2937e61cf7262296cc52738520273bc75d"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.3+1/libcgal_julia.v0.17.3.i686-w64-mingw32-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
git-tree-sha1 = "e1c2aacc44c7052f95aa529265b486724d89bf07"
os = "macos"

    [[libcgal_julia.download]]
    sha256 = "e8270679902f0503008c2d21b43a70b4b86f24a232843630c33ff7c884794a92"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.3+1/libcgal_julia.v0.17.3.x86_64-apple-darwin.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e1925b2209c27e806168726e275c52c5e8c31208"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "e9e0b2a60694505e98355f6cbbf9de5d7ee15f9cb5b7478d680cc4522b43a3fc"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.3+1/libcgal_julia.v0.17.3.x86_64-linux-gnu-cxx03.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a4c9994ee41eda79898cfb8ae158dda101bca1ea"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "1284f77bd088d7644a5610fc77db24bc5661d3ec4256d9e0ddec5499a0ccbbda"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.3+1/libcgal_julia.v0.17.3.x86_64-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cefff96cab298b9598911d7b8ef99760ec338280"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "9397a383a683735a3a4e3f31de4dbaeb34a19ce1afd123d0a605cf0c6bca999c"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.3+1/libcgal_julia.v0.17.3.x86_64-linux-musl-cxx03.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ef1c7473ae90e05c6c846b93fbd3871075c422a7"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "dce574dd19d985151aa885e519c5c3731d175e576d4e7b0952d7ca7ba6b0518c"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.3+1/libcgal_julia.v0.17.3.x86_64-linux-musl-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
git-tree-sha1 = "4ef734679654b2f5db1d2a72d5fe8dd53eee1e48"
os = "freebsd"

    [[libcgal_julia.download]]
    sha256 = "1b0a0b993845ce13d1071e16340b50757f2d1d26242cc7e760524651bb498508"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.3+1/libcgal_julia.v0.17.3.x86_64-unknown-freebsd.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3c592b6bde49d15cfbd5f9d5ec2af3f13da3af6c"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "b2967d8edeacc393532d4960553221ad2751eafedab6ed69007687c27aa3767e"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.3+1/libcgal_julia.v0.17.3.x86_64-w64-mingw32-cxx03.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3ab64acdb46069b098bca7cf9d9843e4aa6078a4"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "95282e91558952a70326023404156b9371b692632c7515144daf9ace38a9ef6e"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.3+1/libcgal_julia.v0.17.3.x86_64-w64-mingw32-cxx11.tar.gz"
