[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "df4f7b7bc48ca5ccd9da602311aae1328c438c74"
os = "macos"

    [[libcgal_julia.download]]
    sha256 = "0fb073026cb3a4d16f571c5e5dc9dece6484d0baea11c7630bd7a65cbb12e40e"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.6.2+0/libcgal_julia.v0.6.2.x86_64-apple-darwin14-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f8e843e6a81622cf73d5d1f77cac54ad037537d9"
os = "macos"

    [[libcgal_julia.download]]
    sha256 = "ca0637d223eb86f7854cd27f8d9724da082c63c245cdeab01ec27b73e3a0a8e0"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.6.2+0/libcgal_julia.v0.6.2.x86_64-apple-darwin14-cxx03.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f31e06553ccd2536266050a38af68a1013715e12"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "a098db308f117ee812da8d00fbf0cfc904114921ea7237e956583785b81d1610"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.6.2+0/libcgal_julia.v0.6.2.x86_64-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4306c327227f1bddfc4b5f22ba0063f6ec5d826b"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "a4e50fed56b496e4d912c7e064d47578a5a7999f8e31ef22a865e5c542a7c570"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.6.2+0/libcgal_julia.v0.6.2.x86_64-w64-mingw32-cxx03.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3ce93fd740a62aae65b7bb59c366459c1014aa7f"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "9caf9c2f4164b0eb7752208c27c291a320ec9ea51a32f2e3b294bde0647ba91f"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.6.2+0/libcgal_julia.v0.6.2.x86_64-w64-mingw32-cxx11.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "942cb2c40b78018cbc73320a069009dcbbffac8f"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "9c9cb6273f6b37288bdbab95b4a282f294fa1a73241edf4ef51b0bed257b0765"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.6.2+0/libcgal_julia.v0.6.2.i686-w64-mingw32-cxx03.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "34381d82f1dbf1fd98bd9e730e492c2dd2dfa52f"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "f65e2d6c612e5d2e7728eb10864dca8ce3a0c6cf9903741e72e2c687ed6c335b"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.6.2+0/libcgal_julia.v0.6.2.i686-w64-mingw32-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d9dfcfc1ee5b7a9db9b251e4ae0883017bf359e2"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "8c40d5fbdbe10a5e45ce3d99bd3f1a6e3f29f5ef93f7e89cd99b7f028867af29"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.6.2+0/libcgal_julia.v0.6.2.x86_64-linux-gnu-cxx03.tar.gz"
