[[libcgal_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "23d7a05257ab6a793630e1487f9500036919efe0"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "f32aa9547ea1cb8ea5db7961f77e250b42d0f8af9ba829dfa0dbb1e8fbcfbc34"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.105+0/libcgal_julia.v0.16.105.aarch64-linux-gnu-cxx03.tar.gz"
[[libcgal_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "83da3481cd24bd4283dafe3236ab9e499a0b096d"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "94850150ced8e68026da3c36957508d93e2378f418ac11f2e4a746bcbd12c3fa"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.105+0/libcgal_julia.v0.16.105.aarch64-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a2cb191c236dff2e895fef11e0871b8e7e843bbb"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "64bd590b887fa5bc88e02212cdbbe9421007e660de3c95795873bfe986e5233f"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.105+0/libcgal_julia.v0.16.105.aarch64-linux-musl-cxx03.tar.gz"
[[libcgal_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "19682b2e45707333b4435abfde1f2d513b7df590"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "f22517557c19d9fe757999fe190d9aae94715f0d94c26e07f753e39cb22a8023"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.105+0/libcgal_julia.v0.16.105.aarch64-linux-musl-cxx11.tar.gz"
[[libcgal_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9a2f0eaf63cffc2d85606b85c4f359aaf87e0d77"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "94206529db544b803b4d5f274d2e069ec44c36a665eb8229f20951838497cb80"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.105+0/libcgal_julia.v0.16.105.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libcgal_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "62e9755b2f366b9d0201d275caee41d56b2549ad"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "3483106ad471e810073382470452966d57657fb3e1b928413c26eccaaffac472"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.105+0/libcgal_julia.v0.16.105.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libcgal_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fd6a1ae5df007002584b9d587db6cb9ffddaeffa"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "9506c041d614d789753e1768883f2c1ba109f45e240afb31fb0f7f6778a3e84c"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.105+0/libcgal_julia.v0.16.105.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libcgal_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2f7f44617c57667933c48a4dd90d0c4d4d5d687d"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "e72f2285457105f04717ae094be363ca2d213d98005c64aa49987b962153c697"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.105+0/libcgal_julia.v0.16.105.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d4892021b2309b3d25296e63f045b288e2a36d10"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "3b01116eacb6b3f0a497444b3ed878b855b6bfaecf27e1980124159b871c9d62"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.105+0/libcgal_julia.v0.16.105.i686-linux-gnu-cxx03.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "26fcfb61150210b5fbd76f5f03b6857139c899f0"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "064fefeddf635f730383f949a2d098b42eceed4e8c78c9b61c1767e0cbc8f5ea"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.105+0/libcgal_julia.v0.16.105.i686-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0dfbc07e82c431cace8b2b2c54ab737e89cf1e5b"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "62fbdd3470225988d45b424532922d1214ce4958f4ffd5205c4bc434adc38921"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.105+0/libcgal_julia.v0.16.105.i686-w64-mingw32-cxx03.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "92a88460b728ee362c4fda4549ae92f379308c78"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "591450e19062e3839bea2a379a40299e4026715b12f6301b0bbbd49c5a9bdf0a"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.105+0/libcgal_julia.v0.16.105.i686-w64-mingw32-cxx11.tar.gz"
[[libcgal_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "76ef282f7cc0ed7bd8f48765c8c2df519b029054"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "f2c54fba11659c02014720735f71700e5244bdeb094f2ac7b79c7202f095d22a"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.105+0/libcgal_julia.v0.16.105.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libcgal_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "77bdd4106840d5e30a245ae483a4fc5fe1016ff5"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "7b21a46a5b92e0bc04157e8ec095a623adf602c7c49f3a6de8c111f08e12a82c"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.105+0/libcgal_julia.v0.16.105.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
git-tree-sha1 = "7ca3e6f23c9f8bbcead2a0bb02713431e82a302b"
os = "macos"

    [[libcgal_julia.download]]
    sha256 = "88d6d73b82b13b2613ae0c66c4553aab0a0f2182690b195cd8a458f87f70ae96"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.105+0/libcgal_julia.v0.16.105.x86_64-apple-darwin.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9ab82c20a0a9cc1ed5bdda887f286a0aa4c8292d"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "bb6bc1220bccdb4fbd6b1d62e2d9f122567ba0a5574e1f77f237c30dbb395ed6"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.105+0/libcgal_julia.v0.16.105.x86_64-linux-gnu-cxx03.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "af31e8a9657e9ad0b654c73bb7f697a8e0b68711"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "2a2d3268c5a58f319c03618056e03604152fd2a4db5d8dc0f1f2905f28265f92"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.105+0/libcgal_julia.v0.16.105.x86_64-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a654a7699eb5536e6516e2bf1574ad45c8d28287"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "ec06c0a5507a55d0300a1aa24ee5df8271400eed6a635793dbae0ddf34e22f7f"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.105+0/libcgal_julia.v0.16.105.x86_64-linux-musl-cxx03.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "84590a31bb0a04142df3f25ee7b3633fc5e89874"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "982d32151dab3c158d94bdc8115d7a4dccc07efb1180257981bab8649bd13c6c"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.105+0/libcgal_julia.v0.16.105.x86_64-linux-musl-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
git-tree-sha1 = "af46334ba7c21b34ac55a681eae9f139be16edd1"
os = "freebsd"

    [[libcgal_julia.download]]
    sha256 = "42726f5f785fc8b04b2c82c7a58cdde7bf1c66d7e37311271b248ac908d64388"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.105+0/libcgal_julia.v0.16.105.x86_64-unknown-freebsd.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d7af23522cf8dad7332b1a958b2f091394f363e3"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "3dec20492e7ae097bb81efbac9a5cc77735e5dbc7de598215a9a03e036957270"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.105+0/libcgal_julia.v0.16.105.x86_64-w64-mingw32-cxx03.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ea810d33ee7105b33aa3593c9a1b50bc6684d9dd"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "e5cc3242ed7cc6042fa4410c0e2fb7780e14a1e171d11662f1ac15db582a8f7e"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.105+0/libcgal_julia.v0.16.105.x86_64-w64-mingw32-cxx11.tar.gz"
