[[libcgal_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eeb939641e61b053bab63c6f947cc5e1588b6d16"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "9ef9ed0d3e72fa39a759047d8208d1f7e2cd821f10c8a3501862a6e3da2a7326"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.106+0/libcgal_julia.v0.16.106.aarch64-linux-gnu-cxx03.tar.gz"
[[libcgal_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d389b20850bb5c79263319bc5be1cda6a3469381"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "091a2b854dcad7d6c70bddb810d0890739a2ad4bfcf2b648930639c932f4db7b"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.106+0/libcgal_julia.v0.16.106.aarch64-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f1cc5a51dd056ee6b6c8570ce5270e46cd5916e9"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "c47f036c1e38018662959786793bbade0449ec59cbc06062ae4fecc83210a3ee"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.106+0/libcgal_julia.v0.16.106.aarch64-linux-musl-cxx03.tar.gz"
[[libcgal_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a07d7af69596f6a16fa90794a695007f8c91591e"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "b02bd86828681bf069dde549a8c974b018b94ce89dac6b237f5a2ed8fb4d3d79"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.106+0/libcgal_julia.v0.16.106.aarch64-linux-musl-cxx11.tar.gz"
[[libcgal_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a4f1846c8e461eceeca5b28de046b151a6867135"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "7980583676a8727447604e62478ae0cc6e0d5e27c51833df272baffc7f7e451b"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.106+0/libcgal_julia.v0.16.106.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libcgal_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "babe28a0a1bf7dcbd2ef9d2ff1223f888b755f64"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "1a029425b3e14ecf1a2fd8d72099978fef05e154db44e84ea8c07f531e552464"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.106+0/libcgal_julia.v0.16.106.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libcgal_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "19b5196eaf2ba474d7612062aacdd9e97dc8ea48"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "0161f31747d3f6cb0ab8d96ab75f235316bdd8ad105472f4400dcc5ba28d2450"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.106+0/libcgal_julia.v0.16.106.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libcgal_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dfa10289690adc93a64b75a69916c8b3cc66c64d"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "d9d639c98608821da23075bca5a253f1898e6d9f3223644b8653f9d8327c4b5e"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.106+0/libcgal_julia.v0.16.106.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9d59dff73c679aa41b4a2f350d197ed369256be7"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "23386fdf8d71521705dd5bf764778e76295b4a4f0e574c3762ece37d0f33c080"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.106+0/libcgal_julia.v0.16.106.i686-linux-gnu-cxx03.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4a74cb5c4e391c409bec5d0f10d2fffc745ef449"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "c192657afcfcba2472405b17b07d11973338c9faedd19f5dec5ba4f1394143fd"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.106+0/libcgal_julia.v0.16.106.i686-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7772199933eceb478dbbbf697a1b7b5faf600eff"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "daa252d389617f84a6f2ee938d726baaf7432ed5de1433f383936f113d965be2"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.106+0/libcgal_julia.v0.16.106.i686-w64-mingw32-cxx03.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "51918364f345649193e0e688113998549cdbfab3"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "572c2ad8ca585a1583fb604b63a6613c4c8d0989fc28a036414186272a25b5cc"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.106+0/libcgal_julia.v0.16.106.i686-w64-mingw32-cxx11.tar.gz"
[[libcgal_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4ef53e029749bf31fe898ff638a5762ea00e689c"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "ed9c13e0ff0d82f44ae03771ecfcbf62d2a1c88073126681f8c3638d3eaf95e1"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.106+0/libcgal_julia.v0.16.106.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libcgal_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "95fd9c91a6729e357ba06e3839611a6d913b0f65"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "5abfd526ea084e6e8b4a780d7ca49d66a7636d4a4f315521c876ad7f3cb9fb19"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.106+0/libcgal_julia.v0.16.106.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
git-tree-sha1 = "f1bf7f1643e685ebd2173679a3922de512fcb30c"
os = "macos"

    [[libcgal_julia.download]]
    sha256 = "89458fe98fe7f9f28eabf262ff707c4706a4e8d86038a7539ee9b58abd5964ad"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.106+0/libcgal_julia.v0.16.106.x86_64-apple-darwin.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0e9c019aec9cdb7ff78b5cdf9a51bfad47313035"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "0a2d0711aa8830d7bae8372aed106a93a3f1c7351daff7e0bfd28b2aa0d1f58e"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.106+0/libcgal_julia.v0.16.106.x86_64-linux-gnu-cxx03.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c8ae8ef1b34cf5c6146bf321958309775a4675dd"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "d05d3d4e6e13d88d05439c9334f2228c532e4e85c8d1c6ee85713505b8c22bc0"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.106+0/libcgal_julia.v0.16.106.x86_64-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c80be44890e8015a3051ae63d5fb8d97bd23309b"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "31c878e433470f157d3baaa3fd4701b938be3f095c08f058e314bdb2f7f58424"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.106+0/libcgal_julia.v0.16.106.x86_64-linux-musl-cxx03.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3447f18bed6b8020e90de28003dbe0a6f629d784"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "246697e31f0046f757b1fc1b375ac91ea8ddb8392e57e3668c31a995c2c824bb"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.106+0/libcgal_julia.v0.16.106.x86_64-linux-musl-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
git-tree-sha1 = "df85e201a482df9e555541ca96ffd3abb8e93f8b"
os = "freebsd"

    [[libcgal_julia.download]]
    sha256 = "060a01ed1fd6e09313a9e09c5cea8aabaab63336b7c99e4d22fa8cbca2b8baaa"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.106+0/libcgal_julia.v0.16.106.x86_64-unknown-freebsd.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "723450ee0dc8a768a849f3c7df655b743e86575f"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "81336869d9b0db545751965a3df07b60a1c8df179e8e503d5ea0bd8c6d42a6cc"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.106+0/libcgal_julia.v0.16.106.x86_64-w64-mingw32-cxx03.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b67b7fc23ddb5cb5af7bfa690fb1bfbe95c4e3b5"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "0aff05e996d4f0d427bb6ba9a361e0fc6dd7297ea0be6c9c35c0361f239d6740"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.106+0/libcgal_julia.v0.16.106.x86_64-w64-mingw32-cxx11.tar.gz"
