[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "90950dde529a11086d19a11c952c4635c51546b7"
os = "macos"

    [[libcgal_julia.download]]
    sha256 = "7150fe7e7a7929b8b2d404d98e03f2c34346a408d45c96a7562d9242d2728c0b"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.5.1+0/libcgal_julia.v0.5.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6ec0eaf6f3ef53ac2e5c3885db0c04c6212d76de"
os = "macos"

    [[libcgal_julia.download]]
    sha256 = "dddc9cb4d3430eecec1f930b0b8742a10abd5f2679642e6be56ad23fd8ece58c"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.5.1+0/libcgal_julia.v0.5.1.x86_64-apple-darwin14-cxx03.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2401dc3723463ee16e49540a822a88026c135a14"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "b485d50303dfe32b86a105f7d45e3ed4a093b8abc6dd9ff33c5150ca79dc30c2"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.5.1+0/libcgal_julia.v0.5.1.x86_64-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "20889ea6733475e5f1fd2c8d2d3f0b37492a604d"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "426befabbd9aa6ae2b1e0ba4d84620224cc97a0d44e1b669446101e374a1d725"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.5.1+0/libcgal_julia.v0.5.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bb2593ac6211f1ca9223e091d033e9c6bb17d59a"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "19eb283e401d06f672f1808d35edd9c43af0a7e6c398d8cd18e707ff80e80f05"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.5.1+0/libcgal_julia.v0.5.1.x86_64-w64-mingw32-cxx11.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b229ab17b30f0a9f8d252b934e641f8743c30261"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "01d69a20b153c2ffb02f849a66097871c5bff3206ae8100089a7429f9ce7b73a"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.5.1+0/libcgal_julia.v0.5.1.i686-w64-mingw32-cxx03.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "55f49db6a30455031502148080e9afc2c85e515a"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "2ce8f170ec544b138470862745919d81e518614e44c3d89d1c7cc34367a95aa7"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.5.1+0/libcgal_julia.v0.5.1.i686-w64-mingw32-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f05872779379c8c62851295a1734156da8e631ab"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "801654a837a5f404cab95fd30b62f7198400bf5d6af865250a8066c7f711be7a"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.5.1+0/libcgal_julia.v0.5.1.x86_64-linux-gnu-cxx03.tar.gz"
