[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dfe4b75d7f477af957de08fcc84744317ada70ac"
os = "macos"

    [[libcgal_julia.download]]
    sha256 = "aff4f70c2406ba63179baa86a2ea41fe32ac5a08c41e1ed87082de59b4947553"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.6.1+0/libcgal_julia.v0.6.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e51620a76f75ad9ff88a33772cbbade5f77e0dfd"
os = "macos"

    [[libcgal_julia.download]]
    sha256 = "000a029ee479d87aaae70e9fd4eb33210e5c95cae8923c3d42d6f8e4cd59cb30"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.6.1+0/libcgal_julia.v0.6.1.x86_64-apple-darwin14-cxx03.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dc49d60d0679123830a1e9f7919f8c74383a65aa"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "58f2a1492db3a29af51bf65100b5be70d9f277f512060f5efcc3f4b8ae281afd"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.6.1+0/libcgal_julia.v0.6.1.x86_64-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dbf331391f7a0533a49d22828832a9af08fadb1e"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "6827c4635dde4f8e0e738ed4d45804938f2402edad1b67f7af78edf90bfb052c"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.6.1+0/libcgal_julia.v0.6.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0e9ae06be3a2f5fd56f15d995009d4858d262171"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "b98044e7238034f956558cee67fa09c8df646b1f6726b358279ad039889b5f0d"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.6.1+0/libcgal_julia.v0.6.1.x86_64-w64-mingw32-cxx11.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "401e612c65478aa16ce02710c3faf0aa02162367"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "fd464c4daea0629eb8459957f7cd67a50e94f1c6dcc45914fae9deab5bcd3af5"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.6.1+0/libcgal_julia.v0.6.1.i686-w64-mingw32-cxx03.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "55222e06857025d449cb8f6c063aa54a0720cefc"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "8d6ffc305051442f5164b72ba292f081728d07de818eb9ee42ad4e08911fd365"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.6.1+0/libcgal_julia.v0.6.1.i686-w64-mingw32-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "266f09ab3fce85bbe55c7da957959f6dd0f878fc"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "b19afb7341c41a7afae3bae731b82b8858e9ef7f725654fec9688ce215601485"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.6.1+0/libcgal_julia.v0.6.1.x86_64-linux-gnu-cxx03.tar.gz"
