[[libcgal_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "46e984e0f0cef68964b1c09fc2034630446bebec"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "aa0dbbcb01eb35eefe34840f4cfa384d86d6be297ea01c34b3fd41cfa92f584d"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.4+0/libcgal_julia.v0.17.4.aarch64-linux-gnu-cxx03.tar.gz"
[[libcgal_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "782c80a344b977bd2a10e6dc08def47f03d2459e"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "3e3b07775d34403162eb760e60a556b1d91e42bd4c400666de86d48c4564972c"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.4+0/libcgal_julia.v0.17.4.aarch64-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1933f0a5ae311b1edf8fce87e8d91063c9f837cb"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "3568b6bc0b843355eb1c9647d47c9fa2f98c997c3df37157ffb9c09179234bbc"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.4+0/libcgal_julia.v0.17.4.aarch64-linux-musl-cxx03.tar.gz"
[[libcgal_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2f1296afb7716628517f8a18fb3d2ffaffafe909"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "255bbd8756e7e3d742dd7044588556c468e4a0cd6ef2f233fd453e8c0ebf7cdb"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.4+0/libcgal_julia.v0.17.4.aarch64-linux-musl-cxx11.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "392180d9b46bda76cc04bb767d6baa4126968f59"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "9743b239673c15fc23eb4f396e90455c5aa910f63f82f42b8a549d8736273485"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.4+0/libcgal_julia.v0.17.4.i686-linux-gnu-cxx03.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "58b9345059d765198b64c93d5ee516668cb77fee"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "e18a3aabfc636703a529cf25dbd60ff79452baf839a8a083b687aa839f97023b"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.4+0/libcgal_julia.v0.17.4.i686-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6cb498daf3acbb1a59324549d3a37d07c7ea85da"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "25bdbc3354f5238b15767787d511e4b36fb2c411529fa816eefa189e005184bc"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.4+0/libcgal_julia.v0.17.4.i686-w64-mingw32-cxx03.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "90a349f6a935ffda08dce34c14db32c96d4d0d4a"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "006815df733e0174f6c39387f11478b92d4649e7ae0f088fdd9c221b759f0b83"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.4+0/libcgal_julia.v0.17.4.i686-w64-mingw32-cxx11.tar.gz"
[[libcgal_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fa498b652076ce73e10c2edda899f52bc0aaf9ce"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "9b7101bdaf64b4ad6c2e56f82b86a9a9ed6146dcf3b595bd08ae7c478573c22f"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.4+0/libcgal_julia.v0.17.4.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libcgal_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "09efe609a7654b55b2cd4b37d959ae824ce1a703"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "394357996bdf4bea91d4877f3d42dde2b6f37221f19cd6ae8bdcde8a415d53d0"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.4+0/libcgal_julia.v0.17.4.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
git-tree-sha1 = "311124c21ebcd3b20db50773e27c4c60cf295f1f"
os = "macos"

    [[libcgal_julia.download]]
    sha256 = "fb61d27f4096f85e83d6e0e744720802edcd28c6fb5c0dc585581b3dbe73619b"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.4+0/libcgal_julia.v0.17.4.x86_64-apple-darwin.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c5fefde718864facb01a855d72a40990b6de61f0"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "d32a06677c0f641a0ebb4285e9a77f09d4efdd07f446b462ea40cf8f87895344"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.4+0/libcgal_julia.v0.17.4.x86_64-linux-gnu-cxx03.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4ad62264374143197df9b15b112b9669b320d1d4"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "f8cc18705f9ff8f512cce332d629f2e6a97abe06aec9daad661ebfb03ebaf3d4"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.4+0/libcgal_julia.v0.17.4.x86_64-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f6283c3e2126ce3147a786de49726f346ee79011"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "cecdabc3ff1ffffd2d14b4a7e9653cf608a7b85488568e2306f39bd340cda670"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.4+0/libcgal_julia.v0.17.4.x86_64-linux-musl-cxx03.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b4d9a406d4f684d58ae17700303e2f8e852c4d52"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "3c2fb65c109f52bbedd15d637a06516ef4aaece11a3cf147a01195e43a4cdc7e"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.4+0/libcgal_julia.v0.17.4.x86_64-linux-musl-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
git-tree-sha1 = "7530ce11312bae325c221f564e9befeaa2ba8959"
os = "freebsd"

    [[libcgal_julia.download]]
    sha256 = "0ebc26f99b7bb54a25b00f043c5742089bc1e82ce06fc85447cd3778e4692fd9"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.4+0/libcgal_julia.v0.17.4.x86_64-unknown-freebsd.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "692743ef7a87e5a87f981beadaee7fa92bd57a11"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "9babb7f94dc577d13efc778d2039c241ed5c20b83991e6afe481edd6a722dd6e"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.4+0/libcgal_julia.v0.17.4.x86_64-w64-mingw32-cxx03.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e1b17e62392b3f81a40a8755990ea72b5b9aba10"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "2db1cba0c59c5c829c6f93330f056eb34ddd518cd9b7ad73d29a16e6f9580a8b"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.4+0/libcgal_julia.v0.17.4.x86_64-w64-mingw32-cxx11.tar.gz"
