[[libcgal_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0409cdcab4582a7f2da32d55170eaca9ca67d9b6"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "a2be2849006466f2000e1b4cbfbb9408ec30f736522e411aadfff5969f0244bb"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.4+0/libcgal_julia.v0.16.4.aarch64-linux-gnu-cxx03.tar.gz"
[[libcgal_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5b42b724d5efde446e7965722d9c5a69cde38ca2"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "b97f43d181610f236b8ade3df0f95026d4bbe051bbba7c2e4795c323573862f7"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.4+0/libcgal_julia.v0.16.4.aarch64-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e6983dd2e0abba8f4d474143cb07caf3c2ef2493"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "1d4fee18f4caebe10fdf8c8b5d5df2ca1a218fe83080775cadf9424288fe706f"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.4+0/libcgal_julia.v0.16.4.aarch64-linux-musl-cxx03.tar.gz"
[[libcgal_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4c4802cfc4ced76d8028350d7d0193012e2dc553"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "00f990baeca60c3b0bc5d22411bb013537b716222c46f1ca31efdde0e74dd480"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.4+0/libcgal_julia.v0.16.4.aarch64-linux-musl-cxx11.tar.gz"
[[libcgal_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "037ac95e4648ac4da086c94c62862103d694a3aa"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "07478ba67c87c0b23d46caec2a61848d65e2d74d194bd5645fb3cdb4679e9398"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.4+0/libcgal_julia.v0.16.4.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libcgal_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2c235f8a51b181948ba63b1a6fda6183d4fb14d2"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "0b1d6631903a9e5d8d7031690884c32d37b664becd545b316056bf1ed86f6d2b"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.4+0/libcgal_julia.v0.16.4.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libcgal_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "74c511c1403b0ec7dbb421ccc77ffbe881930b5f"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "16c8296d659e44fb4754fd9d343cc4fc7ea56d7057fe10768dd7477a90c689b5"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.4+0/libcgal_julia.v0.16.4.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libcgal_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "416e0250d9afaa6901a6a9cc15a758866887cf8a"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "610117948296255ff42f3030eb6251300ead0850f31d971ff9abe0bd06e3b866"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.4+0/libcgal_julia.v0.16.4.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "79c1c3ca88047f6f577f00bc9eb3579f177799d6"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "3dddc577300c765e84a18573a1450b97a3f28469eb1a2a0923e6e5ab0d24c942"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.4+0/libcgal_julia.v0.16.4.i686-linux-gnu-cxx03.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "261a56acc4f5f6d1ca5f2799e6219b22d611d41e"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "c67160ea523580033fa774af5b44ec3e502e96d9a210317f3d521a6c47936abf"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.4+0/libcgal_julia.v0.16.4.i686-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "77c2a70c4c5f4fc4507a191884f250f87df7ed24"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "d69fc50edf65fbf70fdd8460bb0a8f4a04e9628893b6fe707f0fbef5565824d0"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.4+0/libcgal_julia.v0.16.4.i686-w64-mingw32-cxx03.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5f29fc36bf5c9540c5fda4481928bf9b3f30abc2"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "be201e0cbe9fba463dff95ba5e5dec01d9ceb353242aacba81238c33d04f1098"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.4+0/libcgal_julia.v0.16.4.i686-w64-mingw32-cxx11.tar.gz"
[[libcgal_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f992b7df68a71b51dda3563dc5698e3c5333040c"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "9c9ec8c463f6e702f3b251acb0a2d386285cea848e277265777e3f703624ffb5"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.4+0/libcgal_julia.v0.16.4.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libcgal_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5c6e9ffb72e13962ebc4157092daffa8cfade2f5"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "37a2cb8012ef6319672c9a5d71de1472fe62ed0da0494c3f4b9fb5cde1b0eb65"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.4+0/libcgal_julia.v0.16.4.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
git-tree-sha1 = "9c22f649bc356fef68f3e48c3e21461071dbe536"
os = "macos"

    [[libcgal_julia.download]]
    sha256 = "7b00939430cba703a96bde078a6ebbd65509fad6223eda93510deb7dfb3ea18c"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.4+0/libcgal_julia.v0.16.4.x86_64-apple-darwin.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d680bbcababc567a7e7ef9a226af5a3ce3d25a5e"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "fcf13b3509b4143b0da94271712c2dcea14cd04675aa028e884f26898bebf05d"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.4+0/libcgal_julia.v0.16.4.x86_64-linux-gnu-cxx03.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3e4ee68570f42eea961dd076dd8fbbe2de535430"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "f409316d36a0801759d876989d7a4797d7ba1e910307ba2c469375a303792b27"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.4+0/libcgal_julia.v0.16.4.x86_64-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fefe0058f6e98198bf92ef2ff67991d80e7f10fa"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "7c49c6cc611747ee0f586e0325b3b1a8d364cdb5752904c39e30c6475100fe1d"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.4+0/libcgal_julia.v0.16.4.x86_64-linux-musl-cxx03.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c334248ec770252551c4216728e403f26ac9e4c9"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "bc062632f8bb6fe7e496129330a0bb0d6c9d55b6901232a7b8a018cea93ea4b0"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.4+0/libcgal_julia.v0.16.4.x86_64-linux-musl-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
git-tree-sha1 = "524298aabe1413439d5eadd8aaef04ce621e05a5"
os = "freebsd"

    [[libcgal_julia.download]]
    sha256 = "3f2ed9ae946d0a2395ae4ab8a5355c2de8b1e50cb2b86a86bf2320a11a3a1ce7"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.4+0/libcgal_julia.v0.16.4.x86_64-unknown-freebsd.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5609f9fbacdf0ecb1ee8f64696fe7e1abe654bdb"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "2dbcfebc06c56355aef45c465712e7e4c202b744a9610935c565267f2caac3e7"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.4+0/libcgal_julia.v0.16.4.x86_64-w64-mingw32-cxx03.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ea2d1d9e7558848bb621576e4dfe0dbeb203d56a"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "9b63121d802297276417506e0b243f5b4937db082cfa78701eca0d3db622791f"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.4+0/libcgal_julia.v0.16.4.x86_64-w64-mingw32-cxx11.tar.gz"
