[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6dd79ae41bd0d922e2294c414dc5d3d5f9677c01"
os = "macos"

    [[libcgal_julia.download]]
    sha256 = "de3f14d4d0ef4208564b1b3c6bb724c6f4e44fe72d89b2b1d7423991f58df5a7"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.6.3+0/libcgal_julia.v0.6.3.x86_64-apple-darwin14-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2bbf708422015099a42d62239c56ba5562025604"
os = "macos"

    [[libcgal_julia.download]]
    sha256 = "5a29913e86fce1d678f96341f7df064b5d4dd35caf77b3899191c5028c741e16"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.6.3+0/libcgal_julia.v0.6.3.x86_64-apple-darwin14-cxx03.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0236918002a6dae8d9eb6c14567c9ffe735ba979"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "b1be92d76c3d7b4da4271b9350ca16240d498d473c55add25014ef23e437ecf6"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.6.3+0/libcgal_julia.v0.6.3.x86_64-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fe3175175840af4ebe4281a57acbf503c0b59b18"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "e9b0c8706dc6f08fa73d0109ac88f683677d5709709998208a3c710692bab738"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.6.3+0/libcgal_julia.v0.6.3.x86_64-w64-mingw32-cxx03.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fa52c01446d95101fac512fe3ee576651a6089be"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "4c0f7c13095c002e6fe48e4342d8e98fceef6a46e0313c14b5910443500a6dc6"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.6.3+0/libcgal_julia.v0.6.3.x86_64-w64-mingw32-cxx11.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2deb861d5acd868c6b5734c4db4aa05ca5653b3e"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "ad5236bbb5f26dae739282a617e2b4b8338f400016eda19a078be416ea33f024"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.6.3+0/libcgal_julia.v0.6.3.i686-w64-mingw32-cxx03.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "275f1cbbfde9ec303011739007086f09ad63c0ef"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "de9452fab83fe42383b0b91c909d513b2a8d30bbf0867a8414d6e04136b30b6b"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.6.3+0/libcgal_julia.v0.6.3.i686-w64-mingw32-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "aaf6e87c91a0078734a97d6aeff8c8e6267e6e14"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "1a558042bd24c55ec6b137215073eac7ea90a963d6eac8fdb3eb4b9330447431"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.6.3+0/libcgal_julia.v0.6.3.x86_64-linux-gnu-cxx03.tar.gz"
