[[libcgal_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ed8d923748aa6ede632b168aca0c306ace2b9662"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "83ce91ac0ba5e3bb662e00605893649057f298020fa4d7557e574204b57fd5f9"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.3+0/libcgal_julia.v0.17.3.aarch64-linux-gnu-cxx03.tar.gz"
[[libcgal_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "83ec9af24c99808ab18225b23c11b7aa5b428cbb"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "c175b9e1d956d08f2528d0dc05fabf27977be4cb4b5fdee5a16a605ce0693aae"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.3+0/libcgal_julia.v0.17.3.aarch64-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f9e65c78f51b9eb826201e3f9550fbceaf9a79ac"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "625979e0d08910052a860431e4bb30e5f232cc9fd9cf11c114ac0eec1384bcbb"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.3+0/libcgal_julia.v0.17.3.aarch64-linux-musl-cxx03.tar.gz"
[[libcgal_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bb57e351151963910b5923868098b6da73ffc372"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "b652fae0028aeaf755a702c91b71ac6099c45e3180162f73468fcfe3fbe48458"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.3+0/libcgal_julia.v0.17.3.aarch64-linux-musl-cxx11.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "14a03d91544d553955165eb7b981c894ea5a1dbe"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "35f29a430362a1bff01ca9219b3a386e227e682df6debefd9dca32d05377d93f"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.3+0/libcgal_julia.v0.17.3.i686-linux-gnu-cxx03.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f5c3a4b2e1e1bc23d49fb8a4d0d96151ac95148a"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "b8b00c9ef68e98630017224cc1501aea1fd23bb887706853b886f6df2767d4c8"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.3+0/libcgal_julia.v0.17.3.i686-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7bcb646f3a0f890e8f56950320270136e3513312"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "cdeef3c04ae9fb7f6fccfea0dbe660f5b77292874fee3ce51a3cb2d9336d9283"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.3+0/libcgal_julia.v0.17.3.i686-w64-mingw32-cxx03.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d67d3e47da52257081b4f9ce3234b2db8342cd9e"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "887f34263d6db5b949aaef6923f6b46988de6730d3182bde49331eaf3205834a"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.3+0/libcgal_julia.v0.17.3.i686-w64-mingw32-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
git-tree-sha1 = "39e79ec4f7fa7171f8e0b3c67ebf10f73526f751"
os = "macos"

    [[libcgal_julia.download]]
    sha256 = "37f020123a287c0f3e62e644150f868245a2eb8877adc46c842273ceb7bdc907"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.3+0/libcgal_julia.v0.17.3.x86_64-apple-darwin.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4ad88fd79abcae85af25ca4b8778fbca4b98f41d"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "7f9a3694dca132aeede2e8fa94952496aba676932127f79b0e1ae34ea1c917fd"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.3+0/libcgal_julia.v0.17.3.x86_64-linux-gnu-cxx03.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "23ad3cc558765b155105aa8ccd55fc014b813f9d"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "9526120792707f0818ae7983697b04c7240dcb4168c3bae1b0b0d440867e8acb"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.3+0/libcgal_julia.v0.17.3.x86_64-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cdf667f49e0978b7febcaee4c100fd1fc7979337"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "c71e8400ada169f69fc83113a11cfc81f43c9c87e4c9fd6fa9b201854202db39"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.3+0/libcgal_julia.v0.17.3.x86_64-linux-musl-cxx03.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9d8b654dbff058aab402a8b800fc22e5302055b0"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "3bcd8ebea78ceb5b6da1eb6e63e5a35884310b4d0b0d7736982c6d2a14927736"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.3+0/libcgal_julia.v0.17.3.x86_64-linux-musl-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
git-tree-sha1 = "a86f86ef03e05ea436647c07ceb650dd73515934"
os = "freebsd"

    [[libcgal_julia.download]]
    sha256 = "cbd43b6609459a709f17050daf470dcdbe21f7796cf51e9c1e2a491f597dc1b1"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.3+0/libcgal_julia.v0.17.3.x86_64-unknown-freebsd.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "487b87328a4c7f2c065ec124ffc8f27648c00f78"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "86da9739d48d563fc0507606ce6bcd796231f6efd895c3cc15ae9b6b621a89bf"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.3+0/libcgal_julia.v0.17.3.x86_64-w64-mingw32-cxx03.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6c0d86b7573db31daef2c10d8b41fd58035fd218"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "ac00d42dda12f682a5fff09b3faccccd04e7ab71b01bac0ac8442825a54bb41f"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.3+0/libcgal_julia.v0.17.3.x86_64-w64-mingw32-cxx11.tar.gz"
