[[libcgal_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f5d8f0f29c590fb58b97bb4f4f3a3e99165d88af"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "e25b0daa918c65cfc450e2cf711799c9e82af24264b5dadfe188475f68d9187e"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.103+0/libcgal_julia.v0.16.103.aarch64-linux-gnu-cxx03.tar.gz"
[[libcgal_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e9d0a5bc2ffae548ddf4a66dbb2c3912f6e6f897"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "a2397312e1672e138a15a50186ea3dbb26c1f271cc8dde1d81ecd5614dbe0a40"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.103+0/libcgal_julia.v0.16.103.aarch64-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "264282c1bca34d2519bfcb32e048972f5106e51c"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "b61cbd17c81bdedda5be2f3a497a7e1d490733491be716d5350a636888af4128"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.103+0/libcgal_julia.v0.16.103.aarch64-linux-musl-cxx03.tar.gz"
[[libcgal_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6ff4aa8eba28fef1ce10d252683685ec799f65d3"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "f0ea88a8e72f9c58fca5f616ed5da67ffd9cd0392213d9ffbe0c792b50fa2eca"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.103+0/libcgal_julia.v0.16.103.aarch64-linux-musl-cxx11.tar.gz"
[[libcgal_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2838edf60c532142080fc47b3feec8d37afd7025"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "dedf1b481e98de24cfbf51e9f313fdcf53bef0b5a9e50caed8c7a1086ad23f77"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.103+0/libcgal_julia.v0.16.103.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libcgal_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "38a099f602422dd36ce4bc0edc8a63b7cfcd6a8a"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "a4a44d687c9c4a42731c18cd056a46571757d1522dd145d1f6e6b729d5f95767"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.103+0/libcgal_julia.v0.16.103.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libcgal_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8f4d5761e84cbcaac19611427671c32ce3e54be1"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "336c030bfc5ac22d6b45d39f86689f31bf703bdb5613658726b931f4506df539"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.103+0/libcgal_julia.v0.16.103.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libcgal_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0732a9207a50c27786fa2ff7d1043473cc1d3a03"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "67c4cd41f27b53f403d5c5d012fdab4bebfac2c6ca42d051286a3fec6231f04f"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.103+0/libcgal_julia.v0.16.103.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "025d77d840b36c0e0cf733e5429a8fe90975ad31"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "1415e8ddc3628bd9c205dcd6b777e7c799f5bd82c857a0109dd71fe4d5b4f406"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.103+0/libcgal_julia.v0.16.103.i686-linux-gnu-cxx03.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "75abd14ef698e3cfe31e39db7e06f2003db0d4a5"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "a98f3371045514b334c9852c3e35f62a3f77d749d85a8d7666d79318b7297c1e"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.103+0/libcgal_julia.v0.16.103.i686-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a1f308d645274376adebf62f3a9271694ceabebc"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "dbcb6b61b4e290af1fbca6d3b080fffdecc8055e16b4d7ef57ae7906722c345a"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.103+0/libcgal_julia.v0.16.103.i686-w64-mingw32-cxx03.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e84c2a7c09d28b90779b1b293b33c3ced8b019c3"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "1d5ebc2b84ab17a58f79c41c4ad24611fc191655b5cfbc7a68621dcf489d3ab3"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.103+0/libcgal_julia.v0.16.103.i686-w64-mingw32-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
git-tree-sha1 = "1a051c866415b357187a88bcc5a97f5040734263"
os = "macos"

    [[libcgal_julia.download]]
    sha256 = "9b12e5e753ec64be8a58d6e6fe2e30012ad9ddee958c042f80dad3bf5e54d2dd"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.103+0/libcgal_julia.v0.16.103.x86_64-apple-darwin.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9edb59ea629c3462587c58c9d28e15062102a4b5"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "3d3f56350ae989c3a00ef708e69c4c042ba03bd4fef3bd99e14cd9c704854547"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.103+0/libcgal_julia.v0.16.103.x86_64-linux-gnu-cxx03.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ff6574744c68eaf4ecb2c7b73cbfd8de3dd1a89d"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "d9d6532c77e102869a67156bd93221bf2398b8069e586f695fc526392c47c995"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.103+0/libcgal_julia.v0.16.103.x86_64-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bfc16dfd4cc62ad317503eadb4d85f1c16c0adbd"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "a0a64965ca994b7b78104706a2859b46cdf7e068107e1b2f555c370452b1bfa4"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.103+0/libcgal_julia.v0.16.103.x86_64-linux-musl-cxx03.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0956283ca9331cb7a4398505e748121d3249e04d"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "e23589b170c34d3ab47d8edd20d7fef17334c978d975486867452e1607445ba5"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.103+0/libcgal_julia.v0.16.103.x86_64-linux-musl-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
git-tree-sha1 = "41224dad2ebafdee6368fdb46e3076b844cf8cd0"
os = "freebsd"

    [[libcgal_julia.download]]
    sha256 = "48d2486862d307fd938af740c52190468ffafc88b52223b9a7419b32d97b85e7"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.103+0/libcgal_julia.v0.16.103.x86_64-unknown-freebsd.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b1608a6547ce1ff8ae0e5aeebbd88098a5db2212"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "d68267ebde2e496096224c1db3f1f8bb2e5ce3677e94ae96a9fd99e8f9d000e5"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.103+0/libcgal_julia.v0.16.103.x86_64-w64-mingw32-cxx03.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3dda013515c246c7178bf81262f39853206acfde"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "e8569f18cfc837301ef3fc5021971343ad8457264cbe04c0f32ff37b746747e6"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.103+0/libcgal_julia.v0.16.103.x86_64-w64-mingw32-cxx11.tar.gz"
