[[libcgal_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dc6d42026afdc233fb09e4c9c08c63b825a3e0f3"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "a49b0e86381bd188eb102db1bf9df6eabdf0174fadb3d711d9f0f57f5f046a55"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.7+0/libcgal_julia.v0.17.7.aarch64-linux-gnu-cxx03.tar.gz"
[[libcgal_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9499d884ec0b046a6993217c20e0bb06467d5d2b"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "5816bc4b1e14c264f03b1f0272f7b981fe89da7c6e1f721d9332686bd8188c55"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.7+0/libcgal_julia.v0.17.7.aarch64-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "05aad5d357ec900bcb2736baf92b286cbcb94aec"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "3455997b4c171549d242b0f059e53f1c9570d1e4ec47bfe0cd390dabbff56a0c"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.7+0/libcgal_julia.v0.17.7.aarch64-linux-musl-cxx03.tar.gz"
[[libcgal_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "56533c25c10d6cacd14f47ec7f54624ec795524e"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "cb2c848aba46d8bf312dbbcbe23710048ff8405f3346703fa21f7189b4ca3beb"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.7+0/libcgal_julia.v0.17.7.aarch64-linux-musl-cxx11.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b2d30e165d027d8fb4ce6d5ff5d54d144f533de9"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "704b13d4eff18b9635539194187d7bdef09f6b3f0aa23ce5b0ba2cfd9ae6400a"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.7+0/libcgal_julia.v0.17.7.i686-linux-gnu-cxx03.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c91ab61a8766e791054d5941635e1c7239af18ad"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "ff700246942c639f9ff391e51a98e35c34a023425bae9b65fedbe47143167daf"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.7+0/libcgal_julia.v0.17.7.i686-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "26d432dd93c29e2bc0d6512be2bf78f56c48f4c7"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "81bfa87d31425c5fa6a7b5006970fe0f3012a7d9a51c60764700477e11e72ac4"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.7+0/libcgal_julia.v0.17.7.i686-w64-mingw32-cxx03.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ddf7ecac147464a2d2e5973add65508f44280ade"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "df4b5608cff2bf6c9a70d8a8883b98e54061a3d352f7a087ac435d8640b60867"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.7+0/libcgal_julia.v0.17.7.i686-w64-mingw32-cxx11.tar.gz"
[[libcgal_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0e196df22ebaf42f2916ee8422b38c8b65ca5a3a"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "8baf99a3cf0824fde3d1ff10a8e9a6efcb5eff9daa2b758345854d01a00ef448"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.7+0/libcgal_julia.v0.17.7.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libcgal_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "15b5e43a1c879d6f45e7039e4c501dc027bb09a5"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "bb8d06ba0e01e67fedab940ca42b620085b6812f34ba7ef2b58059991598d210"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.7+0/libcgal_julia.v0.17.7.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
git-tree-sha1 = "0a90284675f0b61678c8c8a86904273ce48ac45f"
os = "macos"

    [[libcgal_julia.download]]
    sha256 = "1485eec8f485c6afa5e0b71b3dfe8fcb8897da67d736eab6704d831e85cf2842"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.7+0/libcgal_julia.v0.17.7.x86_64-apple-darwin.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6247e1bd84189a2750b3a1a7e395c6cb1d8351e6"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "a75b975d89de798b7874afcfe586bf8b9417d48744af40f53b95d0d890cfbbd8"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.7+0/libcgal_julia.v0.17.7.x86_64-linux-gnu-cxx03.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "60f48843647991e7ab6b5cbd67590d5bac49f3cc"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "6e0c1800124161cb34ab7be76ba0081c4c07045026dfecc60d64f0318c377de1"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.7+0/libcgal_julia.v0.17.7.x86_64-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ad58a22da2f17acd69f1384ac735274efa965d44"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "999f1859d6081a394b1312f72a8218b9428f87a6c98e3b7902e3bc3407077317"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.7+0/libcgal_julia.v0.17.7.x86_64-linux-musl-cxx03.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b919be07cc14e95c18dc91f24b65c6ecf5353c39"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "2c5e28305768c4e492222cb3f4b6637026a163a51a729d19020381274bcd237b"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.7+0/libcgal_julia.v0.17.7.x86_64-linux-musl-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
git-tree-sha1 = "f49f8d3b652c69940695c072de0892f0e67ea8a2"
os = "freebsd"

    [[libcgal_julia.download]]
    sha256 = "811e981d68a880dc044ea32dee9a0897c57140656e11fd6dfdacd08ff46e1780"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.7+0/libcgal_julia.v0.17.7.x86_64-unknown-freebsd.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b21daaf1c9343491f7120fdd7adb89921864638b"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "3cafd94e7c340e4e4e24511e3317334f7453ff67fa347f570443606ed5e2215c"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.7+0/libcgal_julia.v0.17.7.x86_64-w64-mingw32-cxx03.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "93e49804ddff6ee36fcd645f466e6f5eb94e7ed5"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "84026fd9174677061f0d4d76b35b9df8f9061340a39bef704180e360da03509c"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.7+0/libcgal_julia.v0.17.7.x86_64-w64-mingw32-cxx11.tar.gz"
