[[libcgal_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9e897b18c1d86d312ab81bd6cabfc3a28e95bd1a"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "16d443120f31d317c2b089cc0f824ebb90271960fcfcc83c40d505da3b8def36"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.5+0/libcgal_julia.v0.17.5.aarch64-linux-gnu-cxx03.tar.gz"
[[libcgal_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9f5ba6d1ffade95e9ad0250f7abe26586f760c77"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "ceec3ae94393512e85f27072b94810ab1c2b55a04a9d02285eeffbde782c5837"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.5+0/libcgal_julia.v0.17.5.aarch64-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "17f77e1fb3255cfb44238a3f9c0f62dff3c4a72b"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "87ef9713574ac1b18ec488ca72cef9a615ec0abd33021ad9cefa45cfeef463c1"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.5+0/libcgal_julia.v0.17.5.aarch64-linux-musl-cxx03.tar.gz"
[[libcgal_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "21784b32e37afaa6ab87b2be6891cbb61e5695e2"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "32480cf2acc712e9b09e6cb2ae2cdb2aa36e626a6506175e4d98a8813d7f306f"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.5+0/libcgal_julia.v0.17.5.aarch64-linux-musl-cxx11.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c3b362ebf1887fc4d0d22c16cbb93dd405a89dad"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "e6681497b142c8bd4bd1289a9c9205a39510ec038bfb40799500483fa6ca0fb5"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.5+0/libcgal_julia.v0.17.5.i686-linux-gnu-cxx03.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a294a7fb497e3bd8a58fa3dcfdb62a853974a501"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "a8013defa4f14ff085d2ce2933a39bb1cdf2e26afda78dd4cf98c059042522f0"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.5+0/libcgal_julia.v0.17.5.i686-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0aa29e4c8dd366c9a1489c3edf4daee7e44a5b94"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "fba9b080991432848f9a0a9ee7035b14b1c905f59af8f315bd67c7a88da64dcc"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.5+0/libcgal_julia.v0.17.5.i686-w64-mingw32-cxx03.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5abca4e2b063a337a5a5dc698b2b3880125e9158"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "33ce628057661ec9a4fee3b1039fe662e39ec59e3420d383a6bf72b59bfa5fc1"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.5+0/libcgal_julia.v0.17.5.i686-w64-mingw32-cxx11.tar.gz"
[[libcgal_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3f6088167d4ee13d41489c5c008faddfaebc2222"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "328bf95cbb9c31e5d45d0020e709af10751b96418ec44b6f852d7bf5e5cb1b33"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.5+0/libcgal_julia.v0.17.5.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libcgal_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "90d01a433bdda50c67bf3ea1c1fe63677aa181f0"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "51df2fefc1d92683b0ad0cb27ae7189c23d0a880c9438c1a1b6534831ce620ea"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.5+0/libcgal_julia.v0.17.5.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
git-tree-sha1 = "b0d5aa0a100589f6eeaaebd59c497be405c36555"
os = "macos"

    [[libcgal_julia.download]]
    sha256 = "17df4a5f7fa945e5a082674abef68955763c9314faee805dc3e204aeeb8b57f1"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.5+0/libcgal_julia.v0.17.5.x86_64-apple-darwin.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5266ad125adae8b54803f44bbbbfb3c9491d37b8"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "17f997f779456dd9401fe576e278fd10b106cbb94aee5d0293f64055e5934050"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.5+0/libcgal_julia.v0.17.5.x86_64-linux-gnu-cxx03.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "777bafc91bfeab4cb72c864fa23ada4f20c792a8"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "f4e88e8f089b74d6bbe73a278ce5d5ceafdf887532e3faf963af92e227f438ec"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.5+0/libcgal_julia.v0.17.5.x86_64-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "162c104fc000db7743f88a0ed3951d58405a2096"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "1abceda22ad00744c03a3d1a62df4526f821a4913c16a58ff3b91c160f5e6244"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.5+0/libcgal_julia.v0.17.5.x86_64-linux-musl-cxx03.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7dc26f6f50525523fc8acd8b068c9b94074d342d"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "27078fc39614bc57c8b65c77d2635082a31fa07cc05d63eaeb06e735d450b848"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.5+0/libcgal_julia.v0.17.5.x86_64-linux-musl-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
git-tree-sha1 = "b66ecab996c8883a264f702d6ffa6baa4c6b20a4"
os = "freebsd"

    [[libcgal_julia.download]]
    sha256 = "51ffad8c1e2431ab7b080ca4b73fe70818ac9b94c803ca6879c56f047a96ae07"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.5+0/libcgal_julia.v0.17.5.x86_64-unknown-freebsd.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0b3bad16a95eb4f702b56c37e3e99b6c52d1672c"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "c87fba54b7edcfcb9fa4eaca532b911f957bf51e3cf8f18a7fac130c8ef096af"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.5+0/libcgal_julia.v0.17.5.x86_64-w64-mingw32-cxx03.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1708176b94a5e22353461e6f3394c28817b0aa07"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "8bf52199541f9d8c30d970e32d44b13fc6610fb3649779ab15916cf1b2a90d3f"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.5+0/libcgal_julia.v0.17.5.x86_64-w64-mingw32-cxx11.tar.gz"
