[[libcgal_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c75244ac9c27ab699d6c8b1887daf3d0b82f9562"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "88a523e6df96494c4a730f52ddea78c9656451d0ed8000ea5f258fcbaa0f9970"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.104+0/libcgal_julia.v0.16.104.aarch64-linux-gnu-cxx03.tar.gz"
[[libcgal_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bd72e4b8f50417a07058d6765f57565ea3e24d04"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "4f9e8949ccb4ca217de5925a397dfb8b2764421cf1fe29a567129e4c97912b37"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.104+0/libcgal_julia.v0.16.104.aarch64-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e29062b40a145bab6c055c26372357f0e227fa81"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "c4b6e2da2c55823f57b343043242bdccd3fa82a206eca25cdea5d9283185b23e"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.104+0/libcgal_julia.v0.16.104.aarch64-linux-musl-cxx03.tar.gz"
[[libcgal_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "18ba9872be939b52fcb2abeab164888b09b076ec"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "4dc2ffcb23f1ce7755093b3d1d58a34ad377b3228aa1d45a74f0decd29ac626a"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.104+0/libcgal_julia.v0.16.104.aarch64-linux-musl-cxx11.tar.gz"
[[libcgal_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2d7060e8e4dcb0659e21acd7e5e8fe2e5eeb4dda"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "190058f00e93068d7f429784eb7ad8480ba5d1491f24ef1d1345c812177a7f33"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.104+0/libcgal_julia.v0.16.104.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libcgal_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5f5f387a5d0aae1c28b19edd44a84122d50d6089"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "6d4cc547cb1d738e9b4754a3ed6522cddf110f68d49e42d9d0b7ee7a80218848"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.104+0/libcgal_julia.v0.16.104.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libcgal_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "33958584b7e2e69a4ec8e40b4892a6c2051be2c3"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "a681c6d1ce90058276e08b179c71fd15e99765f9d98a260e29d00816c4fe1ec7"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.104+0/libcgal_julia.v0.16.104.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libcgal_julia]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f3406d9e77db038f9bd44cf8ee03c39aab6edef8"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "cff2102760ca4036f3967f0128805821e5a1467380b5f1558f1540af53d46bf4"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.104+0/libcgal_julia.v0.16.104.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d27f12d2dab6d77643f2d5d90181471e89a76837"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "2396713042a89f71e9d859f27d458e3f3698ed68ec404a0f7b0392b8f49f1434"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.104+0/libcgal_julia.v0.16.104.i686-linux-gnu-cxx03.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c644098f096abe90ac227865926e64bbd7b82461"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "cc79b23f247249540b08f1c0aa2894c8a3d4f8e828538acf0534619b62e6f739"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.104+0/libcgal_julia.v0.16.104.i686-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e45c9a9470cb9d70124e7e39bec0c95b5d92c45c"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "c8ca9ab5ed6374348ce23b5fd731f56ee6a8ba92ef10b13811400e7657cae76c"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.104+0/libcgal_julia.v0.16.104.i686-w64-mingw32-cxx03.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b6eb594efdacc12cafdd3dad01352fab61a6c83f"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "f418c91f3f3b20a2647e0849d6120cf9b48f0eac84ae321c994a0bc785547254"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.104+0/libcgal_julia.v0.16.104.i686-w64-mingw32-cxx11.tar.gz"
[[libcgal_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f513053f9fda33c3c2a802804ba5f885ce64d803"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "6b3ace8680697ecb90dc4b7f1f2b82ecf04429130e26445092629fc276e83585"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.104+0/libcgal_julia.v0.16.104.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libcgal_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f3f64f18bc1aff78929f22f6a2d6ff2da01ea28e"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "f05f78abf686308fe0fc9eb609649fbf453f7a86b955bd972621c7607fd41644"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.104+0/libcgal_julia.v0.16.104.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
git-tree-sha1 = "3e10ebbda341f169cf117dc631a8dad47f4a5e87"
os = "macos"

    [[libcgal_julia.download]]
    sha256 = "98e64eaa4d438109465af0f4f00ab389a559f85ffdbeea5efd1824b83d373056"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.104+0/libcgal_julia.v0.16.104.x86_64-apple-darwin.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a43c4ea4e127706f1b06b80ba72df229f7d4f008"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "dee8eeaac41222f3f32dfa85bc27cc4dd29c062d3c83b58e9483c93dbaff60ff"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.104+0/libcgal_julia.v0.16.104.x86_64-linux-gnu-cxx03.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ddebb35f2afb6747385bc6c7f04f617cab29cc27"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "ad45ada3c3cf60b3415030c857f141f2089072505551122644eacccc062b4f0d"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.104+0/libcgal_julia.v0.16.104.x86_64-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4c8747c48511a70fd229bf7d64b868a83f2b28a2"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "940ab131010352a06a30e9c9eda24726a7bfb42d2fb5debad54b57045ae4c962"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.104+0/libcgal_julia.v0.16.104.x86_64-linux-musl-cxx03.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e864c087e03533b2894490f04a1c70eecd359a3a"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "76b5cb03a20ff57d2486696d417fed8fccbe94c25d49338ba57b604381404d34"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.104+0/libcgal_julia.v0.16.104.x86_64-linux-musl-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
git-tree-sha1 = "00743003f9dbb4135cd5b680f4d436910638bfba"
os = "freebsd"

    [[libcgal_julia.download]]
    sha256 = "4d8f84f98e2c3749bed3d53100e1f188524ed08352c5ce492aa67e846aca720a"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.104+0/libcgal_julia.v0.16.104.x86_64-unknown-freebsd.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7b8d0d348d7453a0b7b98ad3d8489eac0fa068c4"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "b8756452e8014a340c62a634b7553238bc1e066afbb5671048c2bc65c6d4bf4b"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.104+0/libcgal_julia.v0.16.104.x86_64-w64-mingw32-cxx03.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6228ee583b7ae02fa9ea80f68a74c9bc498b7c70"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "f4374c9626ec00ef2ca72e7118c061e481e8e59ec108f0a6ee74c53637034e24"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.16.104+0/libcgal_julia.v0.16.104.x86_64-w64-mingw32-cxx11.tar.gz"
