[[libcgal_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fe82ea1fe62025d4b050a5b8059d76ed9a6a41e9"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "0167df575a52259d31fa93d55ed6759e3a82c90330f332b2f779451735431c6d"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.6+0/libcgal_julia.v0.17.6.aarch64-linux-gnu-cxx03.tar.gz"
[[libcgal_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "27d6b44f9076bcb410a3d06d7a2840ce57afe9e1"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "9ac78cf1b7cf8aa08b56668fa5f9736044bc07dee45498ed3c2f8b1499c570a0"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.6+0/libcgal_julia.v0.17.6.aarch64-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bc05610d8705184cf8cf93f285f98e3476000138"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "020a1783e188758ce793e14ab715b5ed6dc40db7917c07bb349d330dfb2838c8"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.6+0/libcgal_julia.v0.17.6.aarch64-linux-musl-cxx03.tar.gz"
[[libcgal_julia]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "950a401e71405c428260c4e8727f7434638b5322"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "43c456307c22e5e6e2273fffd71787a701ae75ab4e943a267b3d30310985cfc9"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.6+0/libcgal_julia.v0.17.6.aarch64-linux-musl-cxx11.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bf86aed5ab31e4143ca43ca10b33b5ccbf33cbb1"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "3035ccff9a3dcc8105e5b761656d05f343dd91d1bf4f3faaa98dfe8e11cc37cf"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.6+0/libcgal_julia.v0.17.6.i686-linux-gnu-cxx03.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "03a2d2658228d9138d08694206a16f4690e9273d"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "e5864f7c2f3645bece1d51dd113418e81cbf74a3fed4bb3497f7cc79fe1ff9fe"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.6+0/libcgal_julia.v0.17.6.i686-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f3eaf516e28d7cb41f8af517be84dae01576bf7c"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "0b474f982e3df81c767fad65199d62d7df39cfbd5643db3030aedad881f573fd"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.6+0/libcgal_julia.v0.17.6.i686-w64-mingw32-cxx03.tar.gz"
[[libcgal_julia]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7a67fa195e201a320f327cf57b8e307c517997b6"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "b4e949c0e45096ea458325c9ed2046231186dc9cde7db0f11ac8f46206a83fe1"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.6+0/libcgal_julia.v0.17.6.i686-w64-mingw32-cxx11.tar.gz"
[[libcgal_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "badfd49e2078ab45786b1ea17a5b978b662c8370"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "d32de3767df28b4538b84954e4f8fb25367ba435fcd429399712efc9ccb54100"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.6+0/libcgal_julia.v0.17.6.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libcgal_julia]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8b14a1bf6310d089852d0658847ce303def3371b"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "c5847b5392032a05dba8dd643c24e014d715bdc3ceaa220d2d23871f4a0ccdc6"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.6+0/libcgal_julia.v0.17.6.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
git-tree-sha1 = "08dfc728ac5d719eeb9aee094af93cb8cbe1f4dc"
os = "macos"

    [[libcgal_julia.download]]
    sha256 = "45c117625196d0d832e8aa63f451b1fa4df682f79c3646aab31bd0a8e0c0ed68"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.6+0/libcgal_julia.v0.17.6.x86_64-apple-darwin.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5a0d27af6591a2b307707189655a3773d167f218"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "c57d47196fa3f4d591a81879f49ff9bdf7d50614bb613891a2571cc3e00ba267"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.6+0/libcgal_julia.v0.17.6.x86_64-linux-gnu-cxx03.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "509b39f53dea947b7670955907bd33f84875d73c"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "808355dfb2318713e743daba5df3fdd3ffaf3861b937290b6292bad3a27328b6"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.6+0/libcgal_julia.v0.17.6.x86_64-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "01e2cb91ab01098129670fd5fb1aa91a63dea7b1"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "369c63d2dc5bce9148daa4d677cdb253ff1f0afdf61357ec6f1dc362286b68e0"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.6+0/libcgal_julia.v0.17.6.x86_64-linux-musl-cxx03.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "38530226b15201808200a500c2fd42d3f0ffd910"
libc = "musl"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "f7a973095ba838b3fd2f3023471f04549a7d7fc16e1f89bfb9cf4333a9f5711f"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.6+0/libcgal_julia.v0.17.6.x86_64-linux-musl-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
git-tree-sha1 = "3223f0f1b3ea4fd5233020dbdca1a0cfcd5b72da"
os = "freebsd"

    [[libcgal_julia.download]]
    sha256 = "9e00141fa0d77259f653f6111ca132fee3f797a524d63c71e68538d96aa4a281"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.6+0/libcgal_julia.v0.17.6.x86_64-unknown-freebsd.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0482902c7ec7fac794b3ac49f77ce4e61b554afd"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "cf572fe6df2bf8103e94eb72b8a8693e72d860a93813a09e72b4b4e0faf93e65"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.6+0/libcgal_julia.v0.17.6.x86_64-w64-mingw32-cxx03.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d6dac6dcdd1ebaba6350d85db1152e6a51f5e1a1"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "a5a9f1ee5a1e10333da4dee488b9f3f4a0232c31b0fd595e2332fba07b0f1175"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.17.6+0/libcgal_julia.v0.17.6.x86_64-w64-mingw32-cxx11.tar.gz"
