[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "98a6547d128ed784fe0a156c178c0e4f21c3433f"
os = "macos"

    [[libcgal_julia.download]]
    sha256 = "adbf50be47807caf26748008e37aa26bbed968e881b96e474b36e14c8c9cbbb7"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.14.0+0/libcgal_julia.v0.14.0.x86_64-apple-darwin14-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0710e55c3cf2a84d5bde225443784229d66d1c95"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "2eb9564be2fe13275b9429a354e0aed5b890bfc11f463791c9a61f8edf12e542"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.14.0+0/libcgal_julia.v0.14.0.x86_64-linux-gnu-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d77a813abd86beda02575501494c1ff4352144d2"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "affb46ec9937da0bf5cb6601c9c05efb0786c076977de47ded162d69060791c1"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.14.0+0/libcgal_julia.v0.14.0.x86_64-w64-mingw32-cxx11.tar.gz"
