[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eff63c1ddb5f03c490e2b64106d94a4709a35992"
os = "windows"

    [[libcgal_julia.download]]
    sha256 = "f991662439d591a5cb7812bd9fa8e6e8e057e41e35a5d7eb5c59c6281e988d19"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.9.0+0/libcgal_julia.v0.9.0.x86_64-w64-mingw32-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9aa2cb72d46cfc99ac2f143521923385a50441b1"
os = "macos"

    [[libcgal_julia.download]]
    sha256 = "dc907309a810111e38d0279e9863ec3d827bf1bbcefa419e8a21bbea883b18d9"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.9.0+0/libcgal_julia.v0.9.0.x86_64-apple-darwin14-cxx11.tar.gz"
[[libcgal_julia]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6d54c796876d49cfeff639c595be4fe7dcf98f2f"
libc = "glibc"
os = "linux"

    [[libcgal_julia.download]]
    sha256 = "b35300932d6a20fd06608f4ab1f3007bc8935830b7922862df3f9f570a8dc307"
    url = "https://github.com/JuliaBinaryWrappers/libcgal_julia_jll.jl/releases/download/libcgal_julia-v0.9.0+0/libcgal_julia.v0.9.0.x86_64-linux-gnu-cxx11.tar.gz"
